In [1]:
import numpy as np

In [8]:
a = np.array([[1, 2], [3, 4]])
b = np.array([[5, 6]])

In [9]:
a

array([[1, 2],
       [3, 4]])

In [10]:
b

array([[5, 6]])

In [11]:
np.concatenate((a, b), axis=0)

array([[1, 2],
       [3, 4],
       [5, 6]])

In [14]:
b.T

array([[5],
       [6]])

In [16]:
np.concatenate((a, b.T), axis=1)

array([[1, 2, 5],
       [3, 4, 6]])