In [1]:
import numpy as np

In [2]:
robinho_pts = [0, 0, 0, 0]
malheiros_pts = [100, 50, 10, 20]
joel_pts = [20, 30, 50, 70]
ayrton_pts = [66, 66, 66, 66]

pontos = np.array([robinho_pts, malheiros_pts, joel_pts, ayrton_pts])

In [3]:
pontos

array([[  0,   0,   0,   0],
       [100,  50,  10,  20],
       [ 20,  30,  50,  70],
       [ 66,  66,  66,  66]])

In [4]:
pontos[0]

array([0, 0, 0, 0])

In [5]:
pontos[1][0]

100

In [6]:
my_data = np.arange(0, 20)
print(my_data)

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19]


In [7]:
mt1 = np.reshape(my_data, (5, 4))
print(mt1)

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]
 [12 13 14 15]
 [16 17 18 19]]


In [10]:
mt1[2][2]

10

In [11]:
mt1[2, 2]

10

In [12]:
pontos

array([[  0,   0,   0,   0],
       [100,  50,  10,  20],
       [ 20,  30,  50,  70],
       [ 66,  66,  66,  66]])

In [13]:
pontos.item(5)

50

In [14]:
m1 = ["Python", "eh", "Legal"]
m2 = ["Guido", "Van", "Rossum"]
m3 = [10, 20, 30]

[m1, m2, m3]

[['Python', 'eh', 'Legal'], ['Guido', 'Van', 'Rossum'], [10, 20, 30]]

In [15]:
np.array([m1, m2, m3])

array([['Python', 'eh', 'Legal'],
       ['Guido', 'Van', 'Rossum'],
       ['10', '20', '30']], 
      dtype='<U6')