In [16]:
"""
Dataset: https://archive.ics.uci.edu/ml/datasets/Balance+Scale

Attribute Information:

1. Class Name: 3 (L, B, R) 
2. Left-Weight: 5 (1, 2, 3, 4, 5) 
3. Left-Distance: 5 (1, 2, 3, 4, 5) 
4. Right-Weight: 5 (1, 2, 3, 4, 5) 
5. Right-Distance: 5 (1, 2, 3, 4, 5)

São 625 exemplos, 4 atributos e 3 possíveis classes.
Onde tinha 'L' coloquei 1, onde tinha 'B' coloquei 2, e onde tinha 'R' coloquei 3.
"""

"\nDataset: https://archive.ics.uci.edu/ml/datasets/Balance+Scale\n\nAttribute Information:\n\n1. Class Name: 3 (L, B, R) \n2. Left-Weight: 5 (1, 2, 3, 4, 5) \n3. Left-Distance: 5 (1, 2, 3, 4, 5) \n4. Right-Weight: 5 (1, 2, 3, 4, 5) \n5. Right-Distance: 5 (1, 2, 3, 4, 5)\n\nSão 625 exemplos, 4 atributos e 3 possíveis classes.\nOnde tinha 'L' coloquei 1, onde tinha 'B' coloquei 2, e onde tinha 'R' coloquei 3.\n"

In [17]:
import numpy as np

In [18]:
# x são as entradas e y são as saídas

x = np.genfromtxt("dataset.data", delimiter=",", usecols=(1, 2, 3, 4))
y = np.genfromtxt("dataset.data", delimiter=",", usecols=(0))

print(len(x))
print(len(y))
print(x)
print(y)

625
625
[[ 1.  1.  1.  1.]
 [ 1.  1.  1.  2.]
 [ 1.  1.  1.  3.]
 ..., 
 [ 5.  5.  5.  3.]
 [ 5.  5.  5.  4.]
 [ 5.  5.  5.  5.]]
[ 2.  3.  3.  3.  3.  3.  3.  3.  3.  3.  3.  3.  3.  3.  3.  3.  3.  3.
  3.  3.  3.  3.  3.  3.  3.  1.  2.  3.  3.  3.  2.  3.  3.  3.  3.  3.
  3.  3.  3.  3.  3.  3.  3.  3.  3.  3.  3.  3.  3.  3.  1.  1.  2.  3.
  3.  1.  3.  3.  3.  3.  2.  3.  3.  3.  3.  3.  3.  3.  3.  3.  3.  3.
  3.  3.  3.  1.  1.  1.  2.  3.  1.  2.  3.  3.  3.  1.  3.  3.  3.  3.
  2.  3.  3.  3.  3.  3.  3.  3.  3.  3.  1.  1.  1.  1.  2.  1.  1.  3.
  3.  3.  1.  3.  3.  3.  3.  1.  3.  3.  3.  3.  2.  3.  3.  3.  3.  1.
  2.  3.  3.  3.  2.  3.  3.  3.  3.  3.  3.  3.  3.  3.  3.  3.  3.  3.
  3.  3.  3.  3.  3.  3.  1.  1.  1.  2.  3.  1.  2.  3.  3.  3.  1.  3.
  3.  3.  3.  2.  3.  3.  3.  3.  3.  3.  3.  3.  3.  1.  1.  1.  1.  1.
  1.  1.  2.  3.  3.  1.  2.  3.  3.  3.  1.  3.  3.  3.  3.  1.  3.  3.
  3.  3.  1.  1.  1.  1.  1.  1.  1.  1.  2.  3.  1.  1.  3.  3.  3

In [19]:
from sklearn.model_selection import train_test_split

In [20]:
# Doc: http://scikit-learn.org/stable/modules/generated/sklearn.model_selection.train_test_split.html

x_treino, x_teste, y_treino, y_teste = train_test_split(x, y, test_size=0.3, random_state=42)

In [21]:
print(len(x_treino))
x_treino

437


array([[ 2.,  4.,  1.,  5.],
       [ 1.,  4.,  3.,  4.],
       [ 5.,  1.,  5.,  3.],
       ..., 
       [ 3.,  1.,  5.,  1.],
       [ 4.,  3.,  3.,  1.],
       [ 1.,  5.,  1.,  3.]])

In [22]:
print(len(x_teste))
x_teste

188


array([[ 4.,  3.,  5.,  3.],
       [ 4.,  5.,  3.,  1.],
       [ 2.,  4.,  4.,  1.],
       [ 2.,  4.,  3.,  3.],
       [ 4.,  5.,  2.,  1.],
       [ 5.,  1.,  4.,  1.],
       [ 2.,  2.,  3.,  4.],
       [ 1.,  4.,  1.,  3.],
       [ 5.,  2.,  1.,  3.],
       [ 2.,  1.,  5.,  1.],
       [ 3.,  1.,  4.,  1.],
       [ 1.,  2.,  2.,  2.],
       [ 1.,  3.,  2.,  1.],
       [ 1.,  4.,  4.,  1.],
       [ 5.,  3.,  2.,  3.],
       [ 1.,  4.,  1.,  2.],
       [ 1.,  1.,  1.,  3.],
       [ 3.,  5.,  4.,  4.],
       [ 4.,  1.,  5.,  1.],
       [ 3.,  2.,  3.,  2.],
       [ 2.,  1.,  2.,  2.],
       [ 2.,  1.,  5.,  4.],
       [ 1.,  2.,  5.,  5.],
       [ 5.,  5.,  5.,  2.],
       [ 4.,  3.,  3.,  3.],
       [ 1.,  5.,  3.,  1.],
       [ 3.,  1.,  2.,  3.],
       [ 5.,  4.,  1.,  4.],
       [ 5.,  5.,  5.,  1.],
       [ 3.,  1.,  2.,  2.],
       [ 3.,  4.,  2.,  5.],
       [ 3.,  1.,  3.,  2.],
       [ 2.,  3.,  2.,  5.],
       [ 5.,  3.,  1.,  5.],
       [ 2.,  

In [23]:
print(len(y_treino))
y_treino

437


array([ 1.,  3.,  3.,  3.,  2.,  1.,  3.,  2.,  1.,  1.,  3.,  1.,  1.,
        1.,  3.,  1.,  3.,  3.,  2.,  3.,  3.,  3.,  1.,  3.,  3.,  3.,
        3.,  1.,  1.,  1.,  3.,  1.,  1.,  3.,  3.,  3.,  3.,  3.,  3.,
        1.,  3.,  3.,  1.,  2.,  3.,  1.,  2.,  3.,  3.,  3.,  1.,  1.,
        2.,  1.,  3.,  3.,  1.,  3.,  1.,  1.,  3.,  1.,  3.,  3.,  1.,
        1.,  1.,  1.,  1.,  1.,  3.,  1.,  3.,  3.,  3.,  1.,  1.,  1.,
        3.,  1.,  1.,  3.,  1.,  3.,  3.,  2.,  1.,  3.,  3.,  3.,  3.,
        3.,  1.,  3.,  1.,  1.,  1.,  1.,  1.,  1.,  3.,  1.,  3.,  1.,
        1.,  1.,  1.,  2.,  3.,  3.,  3.,  3.,  1.,  3.,  3.,  1.,  3.,
        3.,  1.,  1.,  1.,  3.,  1.,  1.,  1.,  2.,  3.,  3.,  1.,  1.,
        3.,  3.,  1.,  2.,  1.,  3.,  1.,  3.,  1.,  1.,  1.,  1.,  3.,
        1.,  3.,  1.,  3.,  3.,  3.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,
        1.,  3.,  1.,  1.,  3.,  3.,  3.,  1.,  1.,  1.,  3.,  1.,  1.,
        3.,  1.,  3.,  3.,  3.,  1.,  1.,  3.,  3.,  1.,  3.,  1

In [24]:
print(len(y_teste))
y_teste

188


array([ 3.,  1.,  1.,  3.,  1.,  1.,  3.,  1.,  1.,  3.,  3.,  3.,  1.,
        2.,  1.,  1.,  3.,  3.,  3.,  2.,  3.,  3.,  3.,  1.,  1.,  1.,
        3.,  1.,  1.,  3.,  1.,  3.,  3.,  1.,  3.,  1.,  1.,  1.,  1.,
        3.,  2.,  3.,  3.,  1.,  3.,  2.,  2.,  3.,  2.,  3.,  1.,  1.,
        3.,  3.,  1.,  1.,  3.,  1.,  1.,  2.,  1.,  1.,  3.,  3.,  1.,
        1.,  3.,  3.,  1.,  1.,  3.,  3.,  3.,  3.,  3.,  1.,  1.,  3.,
        1.,  3.,  3.,  2.,  3.,  1.,  3.,  2.,  1.,  1.,  3.,  1.,  1.,
        1.,  3.,  1.,  1.,  3.,  3.,  3.,  3.,  3.,  1.,  2.,  3.,  3.,
        1.,  2.,  1.,  3.,  3.,  1.,  3.,  1.,  3.,  3.,  1.,  3.,  1.,
        1.,  1.,  1.,  3.,  3.,  1.,  3.,  3.,  3.,  3.,  3.,  2.,  3.,
        1.,  1.,  2.,  3.,  1.,  1.,  1.,  3.,  1.,  1.,  1.,  3.,  3.,
        3.,  1.,  3.,  3.,  1.,  3.,  3.,  3.,  3.,  3.,  1.,  3.,  3.,
        2.,  1.,  2.,  1.,  1.,  3.,  3.,  1.,  1.,  1.,  3.,  1.,  3.,
        2.,  1.,  3.,  3.,  3.,  2.,  1.,  1.,  1.,  3.,  1.,  3

In [25]:
y_teste[0]

3.0

In [26]:
from sklearn.neighbors import KNeighborsClassifier

knn = KNeighborsClassifier(n_neighbors=17, p=2)
knn.fit(x_treino, y_treino)
labels = knn.predict(x_teste)
print(len(labels))
print(labels)

188
[ 1.  1.  1.  1.  1.  1.  3.  1.  1.  3.  3.  3.  1.  3.  1.  1.  3.  3.
  3.  1.  3.  3.  3.  1.  1.  1.  3.  1.  1.  1.  1.  3.  3.  1.  3.  1.
  1.  1.  1.  1.  1.  3.  1.  1.  3.  1.  1.  3.  1.  3.  1.  1.  3.  3.
  1.  1.  3.  1.  1.  1.  1.  1.  3.  3.  1.  1.  3.  3.  1.  1.  3.  3.
  3.  3.  3.  1.  1.  3.  1.  3.  3.  3.  3.  1.  3.  1.  1.  1.  3.  1.
  1.  1.  3.  1.  1.  3.  3.  3.  3.  3.  1.  3.  3.  3.  1.  1.  1.  3.
  3.  1.  3.  1.  3.  3.  1.  3.  1.  1.  1.  1.  3.  3.  1.  3.  3.  3.
  3.  3.  1.  3.  1.  1.  1.  3.  1.  1.  1.  3.  1.  1.  1.  1.  3.  3.
  1.  3.  3.  1.  3.  3.  3.  3.  3.  1.  1.  3.  1.  1.  3.  1.  1.  3.
  3.  1.  1.  1.  3.  1.  3.  3.  1.  3.  3.  3.  1.  1.  1.  1.  3.  1.
  3.  3.  1.  3.  3.  3.  3.  1.]


In [27]:
y_teste

array([ 3.,  1.,  1.,  3.,  1.,  1.,  3.,  1.,  1.,  3.,  3.,  3.,  1.,
        2.,  1.,  1.,  3.,  3.,  3.,  2.,  3.,  3.,  3.,  1.,  1.,  1.,
        3.,  1.,  1.,  3.,  1.,  3.,  3.,  1.,  3.,  1.,  1.,  1.,  1.,
        3.,  2.,  3.,  3.,  1.,  3.,  2.,  2.,  3.,  2.,  3.,  1.,  1.,
        3.,  3.,  1.,  1.,  3.,  1.,  1.,  2.,  1.,  1.,  3.,  3.,  1.,
        1.,  3.,  3.,  1.,  1.,  3.,  3.,  3.,  3.,  3.,  1.,  1.,  3.,
        1.,  3.,  3.,  2.,  3.,  1.,  3.,  2.,  1.,  1.,  3.,  1.,  1.,
        1.,  3.,  1.,  1.,  3.,  3.,  3.,  3.,  3.,  1.,  2.,  3.,  3.,
        1.,  2.,  1.,  3.,  3.,  1.,  3.,  1.,  3.,  3.,  1.,  3.,  1.,
        1.,  1.,  1.,  3.,  3.,  1.,  3.,  3.,  3.,  3.,  3.,  2.,  3.,
        1.,  1.,  2.,  3.,  1.,  1.,  1.,  3.,  1.,  1.,  1.,  3.,  3.,
        3.,  1.,  3.,  3.,  1.,  3.,  3.,  3.,  3.,  3.,  1.,  3.,  3.,
        2.,  1.,  2.,  1.,  1.,  3.,  3.,  1.,  1.,  1.,  3.,  1.,  3.,
        2.,  1.,  3.,  3.,  3.,  2.,  1.,  1.,  1.,  3.,  1.,  3

In [28]:
np.sum(labels == y_teste)

163

In [29]:
(labels == y_teste).sum()

163

In [30]:
100 * (labels == y_teste).sum() / len(x_teste)

86.702127659574472

In [31]:
knn.score(x_teste, y_teste)

0.86702127659574468

In [32]:
np.mean(labels == y_teste)

0.86702127659574468