In [1]:
import numpy as np

# Carregando os dados com NumPy
entradas = np.genfromtxt("iris.data", delimiter=",", usecols=(0, 1, 2, 3))
saidas = np.genfromtxt("iris.data", delimiter=",", usecols=(4))

print(len(entradas))
print(len(saidas))

150
150


In [5]:
'''
Iris-setosa: 0
Iris-versicolor: 1
Iris-virginica: 2
'''

# Mostrando as 5 primeiras amostras que são Iris-setosa.
print(entradas[:5])
print(saidas[:5])

print("-----------------------")

# Mostrando as 5 últimas amostras que são de Iris-virginica.
print(entradas[-5:])
print(saidas[-5:])

[[ 5.1  3.5  1.4  0.2]
 [ 4.9  3.   1.4  0.2]
 [ 4.7  3.2  1.3  0.2]
 [ 4.6  3.1  1.5  0.2]
 [ 5.   3.6  1.4  0.2]]
[ 0.  0.  0.  0.  0.]
-----------------------
[[ 6.7  3.   5.2  2.3]
 [ 6.3  2.5  5.   1.9]
 [ 6.5  3.   5.2  2. ]
 [ 6.2  3.4  5.4  2.3]
 [ 5.9  3.   5.1  1.8]]
[ 2.  2.  2.  2.  2.]


In [7]:
# Utilizando 150 amostras para treino, sendo 35 de cada classe.
entradas_treino = np.concatenate((entradas[:35], entradas[50:85], entradas[100:135]))
saidas_treino = np.concatenate((saidas[:35], saidas[50:85], saidas[100:135]))

print(len(entradas_treino))
print(len(saidas_treino))

105
105


In [9]:
entradas_teste = np.concatenate((entradas[35:50], entradas[85:100], entradas[135:]))
saidas_teste = np.concatenate((saidas[35:50], saidas[85:100], saidas[135:]))

print(len(entradas_teste))
print(len(saidas_teste))

45
45


In [10]:
from pybrain.datasets import SupervisedDataSet
from pybrain.tools.shortcuts import buildNetwork
from pybrain.supervised import BackpropTrainer

In [13]:
treinamento = SupervisedDataSet(4, 1)

for i in range(len(entradas_treino)):
    
    treinamento.addSample(entradas_treino[i], saidas_treino[i])
    
print(len(treinamento))
print(treinamento.indim)
print(treinamento.outdim)

105
4
1


In [14]:
# Construindo a Rede
rede = buildNetwork(treinamento.indim, 2, treinamento.outdim, bias=True)
trainer = BackpropTrainer(rede, treinamento, learningrate=0.01, momentum=0.3)

# Treinando a Rede
for i in range(1000):
    
    trainer.train()
    
# Testando a Rede
teste = SupervisedDataSet(4, 1)

for i in range(len(entradas_teste)):
    
    teste.addSample(entradas_teste[i], saidas_teste[i])
    
trainer.testOnData(teste, verbose=True)


Testing on data:
('out:    ', '[0.006 ]')
('correct:', '[0     ]')
error:  0.00001744
('out:    ', '[-0.006]')
('correct:', '[0     ]')
error:  0.00001688
('out:    ', '[0.011 ]')
('correct:', '[0     ]')
error:  0.00005829
('out:    ', '[0.008 ]')
('correct:', '[0     ]')
error:  0.00003492
('out:    ', '[-0.006]')
('correct:', '[0     ]')
error:  0.00001858
('out:    ', '[-0.013]')
('correct:', '[0     ]')
error:  0.00008794
('out:    ', '[0.204 ]')
('correct:', '[0     ]')
error:  0.02084274
('out:    ', '[-0.01 ]')
('correct:', '[0     ]')
error:  0.00004644
('out:    ', '[0.008 ]')
('correct:', '[0     ]')
error:  0.00002939
('out:    ', '[-0.019]')
('correct:', '[0     ]')
error:  0.00017976
('out:    ', '[0.036 ]')
('correct:', '[0     ]')
error:  0.00065630
('out:    ', '[-0.028]')
('correct:', '[0     ]')
error:  0.00038562
('out:    ', '[-0.004]')
('correct:', '[0     ]')
error:  0.00000651
('out:    ', '[-0.022]')
('correct:', '[0     ]')
error:  0.00023270
('out:    ', '[-

0.011785364235876897

In [15]:
# Construindo a Rede
rede = buildNetwork(treinamento.indim, 2, treinamento.outdim, bias=True)
trainer = BackpropTrainer(rede, treinamento, learningrate=0.01, momentum=0.5)

# Treinando a Rede
for i in range(1000):
    
    trainer.train()
    
# Testando a Rede
teste = SupervisedDataSet(4, 1)

for i in range(len(entradas_teste)):
    
    teste.addSample(entradas_teste[i], saidas_teste[i])
    
trainer.testOnData(teste, verbose=True)


Testing on data:
('out:    ', '[0.018 ]')
('correct:', '[0     ]')
error:  0.00016592
('out:    ', '[0.013 ]')
('correct:', '[0     ]')
error:  0.00008944
('out:    ', '[0.023 ]')
('correct:', '[0     ]')
error:  0.00026002
('out:    ', '[0.028 ]')
('correct:', '[0     ]')
error:  0.00039247
('out:    ', '[0.019 ]')
('correct:', '[0     ]')
error:  0.00018098
('out:    ', '[0.017 ]')
('correct:', '[0     ]')
error:  0.00015273
('out:    ', '[0.061 ]')
('correct:', '[0     ]')
error:  0.00187022
('out:    ', '[0.023 ]')
('correct:', '[0     ]')
error:  0.00027189
('out:    ', '[0.035 ]')
('correct:', '[0     ]')
error:  0.00060347
('out:    ', '[0.025 ]')
('correct:', '[0     ]')
error:  0.00030316
('out:    ', '[0.032 ]')
('correct:', '[0     ]')
error:  0.00050016
('out:    ', '[0.015 ]')
('correct:', '[0     ]')
error:  0.00010607
('out:    ', '[0.024 ]')
('correct:', '[0     ]')
error:  0.00028888
('out:    ', '[0.014 ]')
('correct:', '[0     ]')
error:  0.00009678
('out:    ', '[0

0.011428451797968229

In [ ]:
# Construindo a Rede
rede = buildNetwork(treinamento.indim, 2, treinamento.outdim, bias=True)
trainer = BackpropTrainer(rede, treinamento, learningrate=0.005, momentum=0.5)

# Treinando a Rede
for i in range(2000):
    
    trainer.train()
    
# Testando a Rede
teste = SupervisedDataSet(4, 1)

for i in range(len(entradas_teste)):
    
    teste.addSample(entradas_teste[i], saidas_teste[i])
    
trainer.testOnData(teste, verbose=True)

In [ ]:
# Construindo a Rede
rede = buildNetwork(treinamento.indim, 2, treinamento.outdim, bias=True)
trainer = BackpropTrainer(rede, treinamento, learningrate=0.3, momentum=0.9)

# Treinando a Rede
for i in range(10000):
    
    trainer.train()
    
# Testando a Rede
teste = SupervisedDataSet(4, 1)

for i in range(len(entradas_teste)):
    
    teste.addSample(entradas_teste[i], saidas_teste[i])
    
trainer.testOnData(teste, verbose=True)

In [ ]:
# Construindo a Rede
rede = buildNetwork(treinamento.indim, 2, treinamento.outdim, bias=True)
trainer = BackpropTrainer(rede, treinamento, learningrate=0.01, momentum=0.7)

# Treinando a Rede
for i in range(1000):
    
    trainer.train()
    
# Testando a Rede
teste = SupervisedDataSet(4, 1)

for i in range(len(entradas_teste)):
    
    teste.addSample(entradas_teste[i], saidas_teste[i])
    
trainer.testOnData(teste, verbose=True)